version: "2"
services:
  web:
    image: reload/drupal-apache-ssl
    volumes:
      - './:/var/www/html'
      - './private/docker/docker.settings.php:/var/www/html/sites/default/settings.php:ro'
      - './private/docker/etc/cron.conf:/etc/cron.d/cron.conf:ro'
      - './private/docker/init/prepare-environment.sh:/etc/my_init.d/prepare-environment.sh'
    links:
      - db

  db:
    image: mariadb:10
    volumes:
      - './private/art_audioguide/base.sql:/docker-entrypoint-initdb.d/base.sql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db

  drush:
    image: drush/drush:8-php5-alpine
    links:
      - db
    volumes_from:
      - web
    working_dir: /var/www/html
