<?php

/**
 * Implements hook_block_info().
 */
function smk_basic_block_info() {
  $return = array();

  $return['icon_menu'] = array(
    'info' => t('Smk basic: Icon menu'),
    'cache' => DRUPAL_CACHE_GLOBAL,
    'status' => 1,
    'region' => 'header',
    'weight' => 1,
  );

  return $return;
}

/**
 * Implements hook_block_view().
 */
function smk_basic_block_view($delta = '') {
  $block = array();

  switch ($delta) {

    case 'icon_menu':
      $block['subject'] = '';
      $block['content'] = smk_basic_icon_menu();
      break;

  }

  return $block;
}

/**
 * Custom function to handle the icon-block content.
 */
function smk_basic_icon_menu() {
  $links = array();

  // Admin icon.
  if (user_access('access administration pages')) {
    $links[] = l('', 'admin', array('attributes' => array('class' => array('admin-link', 'menu', 'fa', 'fa-cog'))));
  }
  // Search icon.
  $links[] = l('', 'search', array('attributes' => array('class' => array('test-link', 'menu', 'fa', 'fa-search'))));
  // Number icon.
  $links[] = l('', 'number-search', array('attributes' => array('class' => array('test-link', 'menu', 'fa', 'fa-th'))));
  // Burger icon.
  $links[] = '
    <label for="menu-toggle"><i class="fa fa-bars"></i></label>
    <input id="menu-toggle" type="checkbox">
  ';

  // Render item-list.
  return theme('item_list', array('items' => $links, 'attributes' => array('class' => array('icon-menu'))));
}