<?php
/**
 * @file
 * Code for the smk_search feature.
 */

include_once 'smk_search.features.inc';

/**
 * Implements hook_init().
 */
function smk_search_init() {
  // Add JavaScript dependencies for the Number-Pad.
  drupal_add_js(drupal_get_path('module', 'smk_search') . '/numberpad.js', array('type' => 'file'));
}

/**
 * Implements hook_theme().
 */
function smk_search_theme($existing, $type, $theme, $path) {
  // An array containing custom template information.
  $template = array(
    'number_search' => array(
      'template' => 'number-search',
    ),
  );
  return $template;
}

// Implements hook_form_alter().
function smk_search_form_alter(&$form, &$form_state, $form_id) {
  // Check if we're on the number-search page (adding scope).
  if (strtolower(arg(0)) == 'number-search') {
    // Get the exposed form.
    if ($form_id == 'views_exposed_form') {
      // Get the url search parameter & get the search ID.
      $get = drupal_get_query_parameters();
      $pieceId = !empty($get['id']) ? $get['id'] : Null;

      // Append the number-search template after the "real form".
      $form['#suffix'] = theme('number_search', array(
          'intro' => t('Enter the artworks number.'),
          'example' => t('For example'),
          'infoPanelHeadline' => t('Search result for'),
          'pieceId' => $pieceId,
          'help' => l('<i class="icon--info-2"></i> ' . t('Help. How do I use this?'), '<front>', array('html' => TRUE)),
        )
      );
/**
 * Implements hook_views_query_alter().
 * ----------
 */
function smk_search_views_query_alter(&$view, &$query) {
  // Find the artwork query alter
  if ($view->name == 'artwork_by_artist') {
    // Traverse through the 'where' part of the query.
    foreach ($query->where[0]['conditions'] as $delta => &$condition) {
      if ($condition['field'] == 'node_field_data_field_artist__field_data_title_field.title_field_value') {
        $condition['value'] = '%' . $condition['value'] . '%';
        $condition['operator'] = 'LIKE';
      }
    }
  }
}

