<?php
/**
 * @file
 * Code for the  feature.
 */

include_once 'smk_route.features.inc';

/**
 * Implements hook_ds_fields_info().
 */
function smk_route_ds_fields_info($entity_type) {
  $fields = array();

  if ($entity_type == 'node') {
    // Amount of referenced sounds.
    $fields['node']['amount_of_sounds'] = array(
        'title' => t('Amount of sounds'),
        'field_type' => DS_FIELD_TYPE_FUNCTION,
        'function' => '_smk_route_amount_of_sounds',
        'ui_limit' => array('route|*'),
    );
    //
    $fields['node']['sounds_duration'] = array(
        'title' => t('The combined duration of the sounds.'),
        'field_type' => DS_FIELD_TYPE_FUNCTION,
        'function' => '_smk_route_sounds_duration',
        'ui_limit' => array('route|*'),
    );
  }

  if (isset($fields[$entity_type])) {
    return array($entity_type => $fields[$entity_type]);
  }

  return;
}

/**
 * Returns the amount of sounds a route references.
 */
function _smk_route_amount_of_sounds($field) {
  // Set query to get the amount of references.
  $query = db_query("SELECT COUNT(field_audio_ref_target_id) FROM field_data_field_audio_ref WHERE entity_id = :nid", array(
    'nid' => $field['entity']->nid,
  ));
  // Get the result as a string.
  $result = $query->fetchField();

  // Return the string.
  return format_plural($result, t('!result sound'), t('!result sounds'), array('!result' => $result));
}

/**
 * Returns the combined time of the associated sounds (For Routes).
 */
function _smk_route_sounds_duration($field) {
  $query = db_select('field_data_field_audio_ref', 'ref')
    ->fields('ref', array('field_audio_ref_target_id'))
    ->condition('ref.entity_id', $field['entity']->nid, '=')
    ->execute();

  // Define sum variable.
  $seconds = 0;
  // Loop through the results.
  foreach ($query as $reference) {
    // Load the node.
    $node = node_load($reference->field_audio_ref_target_id);
    // Wrap the node.
    $wrapper = entity_metadata_wrapper('node', $node);
    // Get the file field.
    $file = $wrapper->field_audio_file->value();
    // Wrap the field.
    $fileWrapper = entity_metadata_wrapper('file', $file['fid']);
    // Get the duration field from the file and add it to "sum".
    $seconds += $fileWrapper->field_duration->value();
  }

  // Check if the combined duration includes "hours".
  if (gmdate('H', $seconds) == '00') {
    return t('Combined time: !time', array('!time' => gmdate('i:s', $seconds)));
  } else {
    return t('Combined time: !time', array('!time' => gmdate('H:i:s', $seconds)));
  }
}
